# Run with --help flag for help.
# Modified 08/01/2020 by Fabio Marroni
#We compared atlantica and marmorata transcripts. So the transcript "atlantica private" are those absent in marmorata.

suppressPackageStartupMessages({
  library(optparse)
})


option_list = list(
  make_option(c("-I", "--infile"), type="character", default="",
              help="File generated by SNPrelate IBD estimation to be used as input file", metavar="character"),
  make_option(c("-K", "--kinship"), type="numeric", default=0.05, 
              help="kinship to be considered significant [default= %default]", metavar="character"),
  make_option(c("-L", "--maxlength"), type="numeric", default=27, 
              help="Max number of windows to investigate [default= %default]", metavar="character"),
  make_option(c("-S", "--nsim"), type="numeric", default=1000, 
              help="Number of simulations [default= %default]", metavar="character"),
  make_option(c("-O", "--outfile"), type="character", default="", 
              help="output file name [default= %default]", metavar="character")
)

opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

#print("USAGE: $ 01_small_RNA.r -I input dir/ -O summarized output file")

  if (is.null(opt$infile)) {
  stop("WARNING: No infile specified with '-I' flag.")
} else {  cat ("infile is ", opt$infile, "\n")
  infile <- opt$infile  
  }

  if (is.null(opt$kinship)) {
  stop("WARNING: No kinship specified with '-K' flag.")
} else {  cat ("kinship is ", opt$kinship, "\n")
  kinship <- opt$kinship  
  }

  if (is.null(opt$maxlength)) {
  stop("WARNING: No maxlength specified with '-L' flag.")
} else {  cat ("maxlength is ", opt$maxlength, "\n")
  maxlength <- opt$maxlength  
  }

  if (is.null(opt$nsim)) {
  stop("WARNING: No nsim specified with '-S' flag.")
} else {  cat ("nsim is ", opt$nsim, "\n")
  nsim <- opt$nsim  
  }

  if (is.null(opt$outfile)) {
  stop("WARNING: No outfile specified with '-O' flag.")
} else {  cat ("outfile is ", opt$outfile, "\n")
  outfile <- opt$outfile  
  }

  #The default value of kinship 0.05 was chosen because the 3rd quartile of kinship is 0.04, so we just stick slightly above it to be not too 
  #inclusive and not too conservative.
sim_wibd_sig<-function(infile,threshold,outfile,maxlength,nsim,kinship)
{
library("data.table")
nsim<-nsim+1
clusters<-matrix(0,nrow=nsim,ncol=maxlength)
wibd<-fread(infile)
wibd$chrpos<-paste(wibd$chr,wibd$start,wibd$end,sep="_")

#Very nice way to aggregate and computing several summary statistics in one shot.
waggr<-wibd[,.(kinsum=sum(kinship),kinmed=median(kinship),kinmean=mean(kinship)),by=.(chrpos)]
orig_waggr<-waggr
for(bbb in 1:nsim)
{
waggr<-orig_waggr
if(bbb>1) waggr$kinmean<-sample(waggr$kinmean)

waggr$chr<-unlist(lapply(strsplit(waggr$chrpos,"_"),"[",1))
waggr$start<-as.numeric(as.character(unlist(lapply(strsplit(waggr$chrpos,"_"),"[",2))))
waggr$end<-as.numeric(as.character(unlist(lapply(strsplit(waggr$chrpos,"_"),"[",3))))
waggr$window<-NA
waggr$kinmean[is.na(waggr$kinmean)]<-0
waggr$kinsum[is.na(waggr$kinsum)]<-0
waggr$kinmed[is.na(waggr$kinmed)]<-0
mywin<-0
#Stupid loop to only select windows in which the mean kinship is greater than our threshold
for(aaa in 2:nrow(waggr))
{
	if(waggr$chr[aaa-1]!=waggr$chr[aaa]) 
	{
		mywin<-mywin+1
		if(waggr$kinmean[aaa]>=kinship)	waggr$window[aaa]<-mywin
		next
	}
	if(waggr$kinmean[aaa]<kinship)
	{
		mywin<-mywin+1
		next
	}
	waggr$window[aaa]<-mywin
}

waggr<-waggr[!is.na(waggr$window),]
waggr2<-waggr[,.(chr=unique(chr),nwin=.N,start=min(start),end=max(end),mean.kinship=mean(kinmean)),by=.(window)]
waggr2<-waggr2[waggr2$nwin>1,]
if(nrow(waggr2)<1) next
endfill<-min(nrow(waggr2),maxlength)
clusters[bbb,1:endfill]<-sort(waggr2$nwin,decreasing=T)[1:endfill]
}

clusters[is.na(clusters)]<-0
sumcl<-clusters[1:2,]
for(ddd in 1:ncol(sumcl))
{
sumcl[2,ddd]<-sum(clusters[2:nrow(clusters),]>=sumcl[1,ddd])/(nrow(clusters)*ncol(clusters))
}
fincl<-data.frame(Size=sumcl[1,],pvalue=sumcl[2,])
browser()
write.table(fincl,outfile,quote=F,sep="\t",row.names=F)
}




count.overlap<-function(start.1=1,end.1=4845859,start.2=1,end.2=84945)
{
	max.start<-max(start.1,start.2)
	min.end<-min(end.1,end.2)
	overlap<-max(0,(1+min.end-max.start))
	overlap
}

count.overlap.vector<-function(x)
{
	max.start<-max(x[1],x[3])
	min.end<-min(x[2],x[4])
	overlap<-max(0,(1+min.end-max.start))
	overlap
}


sim_wibd_sig(infile=infile,kinship=kinship,outfile=outfile,maxlength=maxlength,nsim=nsim)
